### ISSUE TITLE
Need Help Regarding Training the Datasets

### ISSUE THREAD

**Issue by sensouradeep** [Abdulk084/HybridTox2D#2]
Sir, I need a small help regarding the training of the datasets. I am new to these kind of molecular projects. 

By your advice, I downloaded the SR, NR, and AM datasets, only the smiles files from the links provided by you and put them in separate 3 folders. 
1. For using PadEL, should I provide the path of 1 folder at a time and generate one csv file at a time?
2. After converting the smiles file to the *.csv file, should I use this csv file for the training?

Please help! I need this project. 
Thank you in advance, Sir!

**Comment by Abdulk084** [comment]
1. yes
2. yes
